"""Tests for neotree.formatter.markdown — Markdown wrapper."""

import pytest

from neotree.formatter.markdown import MdOptions, format_markdown


def _assert_fenced_text_block(output: str) -> None:
    """Assert that output is wrapped by a text fenced code block.

    Args:
        output: Markdown output string.
    """
    assert "```text" in output
    assert output.endswith("```")


class TestFormatMarkdown:
    @pytest.mark.parametrize(
        ("mode", "content"),
        [
            ("short", "src/api: user.py, auth.py"),
            ("compat", ".\n├── src/\n└── README.md"),
        ],
    )
    def test_mode_wrap(self, mode: str, content: str) -> None:
        output = format_markdown(content, MdOptions(mode=mode, root="/project"))  # type: ignore[arg-type]
        assert "## Project structure (generated by ntree)" in output
        assert "- root: /project" in output
        assert f"- mode: {mode}" in output
        assert content in output
        _assert_fenced_text_block(output)

    def test_budget_shown(self) -> None:
        output = format_markdown("data", MdOptions(budget=1200))
        assert "- budget: 1200" in output

    def test_no_budget(self) -> None:
        output = format_markdown("data", MdOptions())
        assert "budget" not in output

    def test_defaults(self) -> None:
        output = format_markdown("data")
        assert "- root: ." in output
        assert "- mode: compat" in output
        _assert_fenced_text_block(output)
