"""Golden tests for Markdown output

Markdown output embeds the absolute root path which changes between runs,
so we use content assertions instead of golden-file comparisons.
"""

from pathlib import Path

from neotree.cli import run_ntree


def _run_markdown_case(sample_tree: Path, cli_args: list[str]) -> str:
    """Run ``ntree`` against sample tree with markdown-related args.

    Args:
        sample_tree: Sample tree fixture path.
        cli_args: Additional CLI args.

    Returns:
        str: CLI output.
    """
    return run_ntree([str(sample_tree), *cli_args])


def _assert_md_wrapper(output: str, mode: str) -> None:
    """Assert standard markdown wrapper metadata and fence.

    Args:
        output: CLI output.
        mode: Expected mode value.
    """
    assert output.startswith("## Project structure (generated by ntree)")
    assert f"- mode: {mode}" in output
    assert "```text" in output
    assert output.endswith("```")


class TestMdGolden:
    def test_short_md(self, sample_tree: Path) -> None:
        output = _run_markdown_case(sample_tree, ["--short", "--md"])
        _assert_md_wrapper(output, "short")
        assert "src/api: auth.py, user.py" in output

    def test_compat_md(self, sample_tree: Path) -> None:
        output = _run_markdown_case(sample_tree, ["--md"])
        _assert_md_wrapper(output, "compat")
        assert "├── " in output or "|-- " in output
        assert "5 directories, 6 files" in output

    def test_short_md_with_budget(self, sample_tree: Path) -> None:
        output = _run_markdown_case(
            sample_tree,
            [
                "--short",
                "--md",
                "--budget",
                "1200",
            ],
        )
        assert "- budget: 1200" in output
        _assert_md_wrapper(output, "short")

    def test_short_md_with_count(self, sample_tree: Path) -> None:
        output = _run_markdown_case(sample_tree, ["--short", "--md", "--count"])
        assert "(files:" in output
        _assert_md_wrapper(output, "short")

    def test_md_alone_wraps_compat(self, sample_tree: Path) -> None:
        """--md without --short wraps compat output."""
        output = _run_markdown_case(sample_tree, ["--md"])
        _assert_md_wrapper(output, "compat")
        assert "├── " in output or "|-- " in output
