"""Markdown wrapper for ntree output."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal


@dataclass(frozen=True, slots=True)
class MdOptions:
    """Options for Markdown wrapping.

    Attributes:
        mode: Source output mode, ``short`` or ``compat``.
        root: Root path text for metadata.
        budget: Optional budget metadata value.
    """

    mode: Literal["short", "compat"] = "compat"
    root: str = "."
    budget: int | None = None


def format_markdown(content: str, options: MdOptions | None = None) -> str:
    """Wrap tree content in a Markdown document.

    Args:
        content: Already-rendered tree text.
        options: Markdown wrapping options.

    Returns:
        str: Markdown document with metadata and fenced code block.
    """
    opts = options or MdOptions()

    meta_lines = [
        f"- root: {opts.root}",
        f"- mode: {opts.mode}",
    ]
    if opts.budget is not None:
        meta_lines.append(f"- budget: {opts.budget}")

    header = "## Project structure (generated by ntree)"
    meta = "\n".join(meta_lines)
    code_block = f"```text\n{content}\n```"

    return f"{header}\n\n{meta}\n\n{code_block}"
